server:
    port: 8080
spring:
    application:
        name: bank-service
    
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
            fetch-registry: true
            register-with-eureka: true